# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "lite" ]
    tags:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v -o linux_amd64 ./
      run: go build -v ./...
      run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -v -o windows_amd64.exe ./
      run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -v -o darwin_amd64 ./
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # 将下述可执行文件 release 上去
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
            draft: false
            prerelease: false
          files: |
            linux_amd64
            windows_amd64
            darwin_amd64